Rails.application.routes.draw do
  get 'history_relative/index'
  get 'advs_relative/index'
  get 'notes_relative/index'
  get 'history_user/index'
  get 'advs_user/index'
  get 'notes_user/index'
  get 'main_relative/index'
  get 'main_user/index'
  get 'privacy_relative/index'
  get 'privacy_user/index'
  get 'relative/index'
  get 'patient/index'
	get 'welcome/index'

  get 'history_relative', to: 'history_relative#index'
  get 'advs_relative', to: 'advs_relative#index'
  get 'notes_relative', to: 'notes_relative#index'
  get 'history_user', to: 'history_user#index'
  get 'advs_user', to: 'advs_user#index'
  get 'notes_user', to: 'notes_user#index'
  get 'main_relative', to: 'main_relative#index'
	get 'main_user', to: 'main_user#index'
	get 'privacy_relative', to: 'privacy_relative#index'
	get 'privacy_user', to: 'privacy_user#index'
	get 'relative', to: 'relative#index'
	get 'patient', to: 'patient#index'

	root 'welcome#index'
end
